version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: auction-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis 
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/auction_db?authSource=admin
      REDIS_HOST: redis  
      REDIS_PORT: 6379
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
